"""Local UI assets; no CDN, tracking, external scripts, or arbitrary HTML rendering."""
from dashboard import HTML
STYLE=HTML.split('<style>')[1].split('</style>')[0]
PAGE='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MuxMender · Library workflow</title><style>'''+STYLE+'''
input,select{font:inherit;padding:9px;background:#0c141e;color:#edf3fa;border:1px solid #61768e;border-radius:5px;max-width:100%}input[type=text]{width:100%}label{display:block;margin:10px 0}.controls{display:flex;gap:16px;align-items:end;flex-wrap:wrap}.controls label{flex:1;min-width:120px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:12px;border-bottom:1px solid #344353;text-align:left}td:first-child{max-width:360px;overflow-wrap:anywhere}button:disabled{opacity:.45;cursor:not-allowed}a{color:#77edc4}h2{margin-bottom:14px}dialog{background:#18212c;color:#edf3fa;border:1px solid #70859a;border-radius:10px;width:min(95%,650px)}dialog::backdrop{background:#000a}.primary{background:#1b7059}.path{overflow-wrap:anywhere}#notice{min-height:24px}pre[hidden]{display:none}
</style><header><h1>MuxMender</h1><span>Library workflow</span><a href="/history" target="_blank" rel="noopener">Job history</a><span id="connection" role="status">Connecting…</span></header>
<main><div class="notice">Originals stay untouched. One queued job runs at a time. No automatic installs or CPU fallback.</div>
<p id="notice" role="status"></p><article><h2>1 · Scan a file or folder</h2><form id="scanForm"><label>Absolute media path<input id="source" type="text" required placeholder="Y:\\TV or \\\\server\\Media\\TV"></label><button class="primary">Start read-only scan</button></form></article>
<article><h2>2 · Review recommendations</h2><div class="controls"><label>Saved scan<select id="scans"><option value="">Choose a scan</option></select></label><button id="refreshScans">Refresh scans</button></div><p class="muted">Only SDR H.264 candidates can use this first workflow. HDR, Dolby Vision, unknown color and legacy codecs keep their separate review paths. Savings are unknown until tested.</p><form id="filters" class="controls"><label>Recommendation<select id="actionFilter"><option value="">All recommendations</option><option value="preview-candidate">Eligible for preview</option><option value="needs-review">Needs review</option><option value="keep-as-is">Keep as is</option><option value="specialized-dv">Specialized Dolby Vision</option><option value="probe-error">Probe errors</option></select></label><label>File or folder contains<input id="pathFilter" type="text" maxlength="256"></label><button>Apply filters</button></form><div class="table-wrap"><table><thead><tr><th>File</th><th>Format</th><th>Recommendation</th><th>Action</th></tr></thead><tbody id="rows"></tbody></table></div><div class="row"><button id="previous">Previous</button><span id="pageInfo"></span><button id="next">Next</button></div></article>
<article><div class="row"><h2>3 · Queue & results</h2><button id="dependencies">Check dependencies</button></div><p class="muted">Cancellation retains partial files. After a restart, unfinished jobs need a new approval; they never resume automatically.</p><section id="queue" aria-label="Queue"></section></article></main>
<dialog id="approval"><form id="approveForm"><h2>Approve a separate output</h2><p id="selectedPath" class="path"></p><div class="controls"><label>Operation<select id="kind"><option value="preview">Short preview</option><option value="convert">Full episode</option></select></label><label>Hardware<select id="hardware"><option value="auto">Auto · GPU first</option><option value="amd">AMD</option><option value="nvidia">NVIDIA</option><option value="intel">Intel</option><option value="cpu">CPU · explicit choice</option></select></label><label>Codec<select id="codec"><option value="hevc">HEVC</option><option value="av1">AV1</option></select></label></div><div class="controls"><label>Preview start (seconds)<input id="start" type="number" min="0" value="300" required></label><label>Preview duration<input id="seconds" type="number" min="1" max="30" value="30" required></label><label>Minimum savings %<input id="savings" type="number" min="0" max="99" value="5" required></label></div><p>Exact resolution retained. Audio/subtitles copied. Output and validation stay in a new local job folder. Preview boundaries may include keyframe preroll. Nothing is automatically added to Plex.</p><label><input id="consent" type="checkbox" required> I approve this operation on the selected file, writing a separate output.</label><div class="row"><button type="button" id="dismiss">Cancel</button><button class="primary">Approve & queue</button></div></form></dialog>
<script>
let token='',offset=0,total=0,selected=null,scanId='',busy=false,rowRequest=0;const $=s=>document.querySelector(s);
function el(tag,text){const n=document.createElement(tag);if(text!=null)n.textContent=text;return n}
function message(text,error=false){$('#notice').textContent=text;$('#notice').style.color=error?'#ffb3a7':'#77edc4'}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-MuxMender-Token':token},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data}
const size=n=>n==null?'Unknown':(n/1e9).toFixed(2)+' GB';
async function scans(){const data=await api('/api/scans');const value=$('#scans').value;$('#scans').replaceChildren(new Option('Choose a scan',''));for(const s of data.scans)$('#scans').add(new Option(s.name,s.id));$('#scans').value=value}
async function rows(){const request=++rowRequest;scanId=$('#scans').value;if(!scanId){$('#rows').replaceChildren();$('#pageInfo').textContent='Choose a scan';$('#previous').disabled=true;$('#next').disabled=true;return}const data=await api('/api/rows?'+new URLSearchParams({scan:scanId,offset,action:$('#actionFilter').value,q:$('#pathFilter').value}));if(request!==rowRequest)return;total=data.total;$('#rows').replaceChildren();for(const r of data.rows){const tr=el('tr');tr.append(el('td',r.path),el('td',`${r.video_codec||'?'} · ${r.width||'?'}×${r.height||'?'} · ${size(r.size_bytes)}`));const recommendation=el('td',r.action+' — '+r.reason);tr.append(recommendation);const td=el('td'),b=el('button','Review & select');b.disabled=r.action!=='preview-candidate';b.onclick=()=>{selected={...r,scan:data.scan};$('#selectedPath').textContent=r.path;$('#consent').checked=false;$('#start').value=Math.min(300,Math.max(0,(r.duration_seconds||60)/2));$('#approval').showModal()};td.append(b);tr.append(td);$('#rows').append(tr)}$('#pageInfo').textContent=`${total?offset+1:0}–${Math.min(offset+100,total)} of ${total} matching (${data.scanned} scanned)`;$('#previous').disabled=offset===0;$('#next').disabled=offset+100>=total}
async function queue(){const data=await api('/api/queue');const open=new Map([...$('#queue').children].map(n=>[n.dataset.id,{open:n.querySelector('details')?.open,log:n.querySelector('pre')?.textContent}]));$('#queue').replaceChildren();for(const j of data.jobs){const a=el('article');a.dataset.id=j.id;a.className=j.state;const head=el('div');head.className='row';head.append(el('h2',j.title),el('span',j.state));a.append(head,el('p',j.phase));const bar=el('progress');bar.max=100;if(j.percent!=null)bar.value=j.percent;bar.setAttribute('aria-label',j.title+' progress');a.append(bar,el('p',`${j.percent==null?'Waiting':Number(j.percent).toFixed(1)+'%'}${j.stage_eta!=null?' · Stage ETA ~'+Math.ceil(j.stage_eta/60)+' min':''}`));if(j.error)a.append(el('p',j.error));if(j.result){if(j.result.total_savings_percent!=null)a.append(el('p',`Total savings: ${j.result.total_savings_percent.toFixed(1)}% · ${size(j.result.output_bytes)}`));if(j.result.output)a.append(el('p','Output: '+j.result.output));if(j.state==='verified')a.append(el('p','Validation passed; playback review required.'))}if(['queued','running'].includes(j.state)){const cancel=el('button','Cancel job');cancel.onclick=async()=>{try{await api('/api/cancel',{id:j.id});message('Cancellation requested; files are retained.')}catch(e){message(e.message,true)}};a.append(cancel)}const d=el('details'),summary=el('summary','Latest log'),pre=el('pre',open.get(j.id)?.log||'Open to load log');d.open=!!open.get(j.id)?.open;d.append(summary,pre);d.ontoggle=async()=>{if(d.open){try{pre.textContent=(await api('/api/queue-log?id='+j.id)).text}catch(e){pre.textContent=e.message}}};a.append(d);$('#queue').append(a);if(d.open)pre.textContent=(await api('/api/queue-log?id='+j.id)).text}if(!data.jobs.length)$('#queue').append(el('p','No queued jobs yet. Scan a path to begin.'))}
$('#scanForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{const r=await api('/api/enqueue',{kind:'scan',source:$('#source').value});message('Read-only scan queued.');await queue()}catch(e){message(e.message,true)}finally{busy=false}};
$('#approveForm').onsubmit=async e=>{e.preventDefault();if(busy||!selected||!$('#consent').checked)return;busy=true;try{await api('/api/enqueue',{kind:$('#kind').value,scan:selected.scan,row:selected.id,hardware:$('#hardware').value,codec:$('#codec').value,start:Number($('#start').value),seconds:Number($('#seconds').value),min_savings:Number($('#savings').value),approved:true});$('#approval').close();message('Approved job queued. Original stays untouched.');await queue()}catch(e){message(e.message,true)}finally{busy=false}};
$('#filters').onsubmit=e=>{e.preventDefault();offset=0;rows().catch(e=>message(e.message,true))};
$('#dismiss').onclick=()=>$('#approval').close();$('#scans').onchange=()=>{offset=0;rows().catch(e=>message(e.message,true))};$('#refreshScans').onclick=()=>scans().then(rows).catch(e=>message(e.message,true));$('#previous').onclick=()=>{offset=Math.max(0,offset-100);rows().catch(e=>message(e.message,true))};$('#next').onclick=()=>{offset+=100;rows().catch(e=>message(e.message,true))};$('#dependencies').onclick=()=>api('/api/enqueue',{kind:'dependencies',hardware:'auto'}).then(()=>message('Dependency check queued; no installation.')).catch(e=>message(e.message,true));
async function refresh(){try{await queue();$('#connection').textContent='Local · '+new Date().toLocaleTimeString()}catch(e){$('#connection').textContent='Disconnected';message('Cannot refresh; displayed results may be stale. '+e.message,true)}finally{setTimeout(refresh,3000)}}
(async()=>{try{token=(await api('/api/session')).token;await scans();refresh()}catch(e){message(e.message,true)}})();
</script></html>'''
