"""Batch view sharing the original control room's exact stylesheet."""
from ui import HTML as ORIGINAL
STYLE=ORIGINAL.split('<style>',1)[1].split('</style>',1)[0]
HTML='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MuxMender · Batches</title><style>'''+STYLE+'''
.batch-table{width:100%;border-collapse:collapse}.batch-table td,.batch-table th{padding:15px 20px;text-align:left;border-bottom:1px solid var(--line)}.batch-table th{color:var(--muted);font-size:11px}.table-wrap{overflow:auto}.filters{display:flex;gap:12px;flex-wrap:wrap;margin:22px 0}.filters input,.filters select{padding:10px;border:1px solid var(--line);border-radius:6px;background:white}.batch-table small{display:block;color:var(--muted);margin-top:5px}.live-job{padding:15px 22px;border-bottom:1px solid var(--line)}
</style></head><body><aside class="sidebar"><div class="brand"><span class="brand-icon"><i></i><i></i><i></i></span>MuxMender</div><div class="sidebar-label">Workspace</div><nav><a class="active" href="/">Batch overview</a><a href="http://127.0.0.1:8765/">Original dashboard ↗</a></nav><div class="sidebar-foot"><strong>Local control room</strong>Read-only · Originals protected</div></aside><div class="workspace"><header class="topbar"><strong>Workspace / Batches</strong><span id="connection" role="status">Connecting…</span></header><main><div class="page-heading"><div><p class="eyebrow">Media operations</p><h1>Batch control room</h1><p class="subtitle">Every episode, from encoding to verification and playback review.</p></div></div><div id="error" role="alert" hidden></div><section class="summary" id="summary"></section><section class="panel"><div class="panel-head"><h2>Current work</h2><span class="tiny">Live stage progress · no moving status bars</span></div><div id="active"></div></section><div class="filters"><select id="batch" aria-label="Batch"></select><input id="search" aria-label="Search episodes" placeholder="Search episodes…"><select id="filter" aria-label="Status"><option value="all">All episodes</option><option value="Passed">Verified</option><option value="Failed">Needs attention</option><option value="Pending">Pending</option></select></div><section class="panel"><div class="panel-head"><h2 id="batch-title">Episodes</h2><span class="tiny" id="count"></span></div><div class="table-wrap"><table class="batch-table"><thead><tr><th>Episode</th><th>State</th><th>Original → output</th><th>Saved</th><th>Verification</th><th>Playback review</th></tr></thead><tbody id="episodes"></tbody></table></div></section><p class="subtitle" style="margin-top:18px">Savings describe encoded file sizes, not free disk space. Automated verification does not imply playback approval. Historical outputs may have been moved or cleaned up.</p><footer class="footer">Read-only monitor · Refreshes every 3 seconds · Existing dashboard unchanged</footer></main></div><script>
const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n};let batches=[],jobs=[];
const bytes=n=>Number.isFinite(n)?(n/1e9).toFixed(2)+' GB':'—';
function render(){const batch=batches.find(b=>b.id===$('#batch').value),rows=batch?.episodes||[];const verified=rows.filter(r=>r.verification==='Passed'),sized=verified.filter(r=>Number.isFinite(r.original_bytes)&&Number.isFinite(r.output_bytes));const old=sized.reduce((a,r)=>a+r.original_bytes,0),out=sized.reduce((a,r)=>a+r.output_bytes,0);$('#summary').replaceChildren();for(const [label,value] of [['Episodes',rows.length],['Verified',verified.length],['Needs attention',rows.filter(r=>r.verification==='Failed').length],['Measured savings',old>0?((1-out/old)*100).toFixed(1)+'%':'—']]){const card=el('div',null,'stat');card.append(el('span',label,'stat-label'),el('strong',value));$('#summary').append(card)}$('#batch-title').textContent=batch?.name||'No batch reports yet';const matches=rows.filter(r=>(r.episode+' '+(r.error||'')).toLowerCase().includes($('#search').value.toLowerCase())&&($('#filter').value==='all'||r.verification===$('#filter').value));$('#count').textContent=matches.length+' episodes';$('#episodes').replaceChildren();for(const r of matches){const tr=el('tr'),name=el('td',r.episode);if(r.error)name.append(el('small',r.error));tr.append(name,el('td',r.state.replaceAll('_',' ').replaceAll('-',' ')),el('td',bytes(r.original_bytes)+' → '+bytes(r.output_bytes)),el('td',Number.isFinite(r.saved_percent)?r.saved_percent.toFixed(1)+'%':'—'),el('td',r.verification),el('td',r.playback));$('#episodes').append(tr)}if(!matches.length){const row=el('tr'),cell=el('td','No episodes match this view.');cell.colSpan=6;row.append(cell);$('#episodes').append(row)}$('#active').replaceChildren();const active=jobs.filter(j=>j.state==='running');for(const j of active){const div=el('div',null,'live-job');div.append(el('strong',j.title),el('p',j.phase||'Preparing'));const pct=j.stage_percent;div.append(el('span',(Number.isFinite(pct)?pct.toFixed(1)+'% · ':'')+(j.completed??0)+' / '+(j.total??'—')+' completed'));$('#active').append(div)}if(!active.length)$('#active').append(el('div','No active jobs. Completed batches remain available below.','live-job'))}
for(const id of ['batch','search','filter'])$('#'+id).addEventListener(id==='search'?'input':'change',render);
async function refresh(){try{const responses=await Promise.all([fetch('/api/batches'),fetch('/api/jobs')]);if(responses.some(r=>!r.ok))throw Error('Cannot reach dashboard');const [b,j]=await Promise.all(responses.map(r=>r.json()));batches=b.batches;jobs=j.jobs;const selected=$('#batch').value;$('#batch').replaceChildren();for(const item of batches){const option=el('option',item.name);option.value=item.id;$('#batch').append(option)}if(batches.some(b=>b.id===selected))$('#batch').value=selected;$('#connection').textContent='Live · '+new Date().toLocaleTimeString();$('#error').hidden=true;render()}catch(e){$('#connection').textContent='Disconnected';$('#error').hidden=false;$('#error').textContent='Connection lost. Displayed results may be stale.'}finally{setTimeout(refresh,3000)}}refresh();
</script></body></html>'''

# Reuse the status dashboard's layout primitives, not merely its colors.
HTML = HTML.replace('<div id="error" role="alert"', '<div id="error" class="global-error" role="alert"')
HTML = HTML.replace('<h1>Batch control room</h1>', '<h1>Processing overview</h1>')
HTML = HTML.replace('Every episode, from encoding to verification and playback review.',
                    'Follow every episode. Verify the results. See what you saved.')
HTML = HTML.replace('<section class="panel"><div class="panel-head"><h2>Current work</h2>',
                    '<div class="content-grid"><section class="panel"><div class="panel-head"><h2>Current work</h2>')
HTML = HTML.replace('Live stage progress · no moving status bars', 'Live processing status')
HTML = HTML.replace('<div id="active"></div></section><div class="filters">',
                    '<div id="active"></div></section><section class="panel" id="batch-insight"><div class="panel-head"><h2>Batch results</h2><span class="tiny">Selected batch</span></div><div class="focus-body" id="insight"></div></section></div><div class="filters">')
HTML = HTML.replace('<table class="batch-table">', '<table class="batch-table history">')
HTML = HTML.replace('<span id="connection" role="status">', '<span id="connection" class="connection" role="status">')
HTML = HTML.replace('<a class="active" href="/">Batch overview</a>',
                    '<a class="active" href="/" aria-current="page"><svg viewBox="0 0 20 20" aria-hidden="true"><rect x="3" y="3" width="5" height="5" rx="1"/><rect x="12" y="3" width="5" height="5" rx="1"/><rect x="3" y="12" width="5" height="5" rx="1"/><rect x="12" y="12" width="5" height="5" rx="1"/></svg>Batch overview</a>')
HTML = HTML.replace('Original dashboard ↗', 'Status dashboard ↗')
HTML = HTML.replace('</style>', '''
.content-grid{margin-bottom:24px}.filters{margin:24px 0 14px;align-items:center}.filters select:first-child{max-width:440px;flex:1}.filters input{margin-left:auto;min-width:210px}.batch-table{font-variant-numeric:tabular-nums}.batch-table th{background:#fafbfc;padding-top:13px;padding-bottom:13px;font-weight:500}.batch-table td{font-size:12px;vertical-align:middle}.batch-table tbody tr:hover{background:#f8faf8}.batch-table td:first-child{font-weight:600;color:var(--ink)}.batch-table td:nth-child(4){color:var(--green);font-weight:600}.state-pill{display:inline-block;border-radius:5px;padding:5px 8px;font-size:11px;font-weight:500;background:#f0f2f5;color:#657180;white-space:nowrap}.state-pill.passed{background:#eaf4ec;color:#237746}.state-pill.failed{background:#fff0e7;color:#a45d20}.state-pill.running{background:#edf3ff;color:#385e9f}.review-label{color:var(--muted);font-size:11px}.live-job{padding:25px 24px;min-height:205px;display:flex;flex-direction:column;justify-content:center;align-items:flex-start;gap:8px}.live-job strong{font-size:20px;font-weight:600;letter-spacing:-.5px}.live-job p{margin:0;color:var(--muted);line-height:1.6}.idle-icon{width:38px;height:38px;background:#edf5e8;color:var(--green);border-radius:50%;display:grid;place-items:center;font-size:19px;margin-bottom:3px}.insight-total{font-size:34px;letter-spacing:-1px;font-weight:600;color:var(--ink);margin:0 0 6px}.insight-sub{font-size:12px;color:var(--muted);margin:0 0 23px}.insight-row{display:flex;justify-content:space-between;gap:12px;border-top:1px solid var(--line);padding:12px 0;font-size:12px}.insight-row span:first-child{color:var(--muted)}.stat-note{display:block;font-size:11px;color:var(--muted);margin-top:7px}.batch-caption{color:var(--muted);font-size:11px}.table-wrap{max-height:620px;overflow:auto}.batch-table thead{position:sticky;top:0;z-index:1}#batch-title{max-width:75%;overflow-wrap:anywhere}@media(max-width:900px){.content-grid{grid-template-columns:1fr}.filters input{margin-left:0;min-width:0;flex:1}.filters select:first-child{max-width:100%;flex-basis:100%}.batch-table{min-width:780px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
</style>''')

# Enhance the shared data renderer using safe DOM/textContent operations.
HTML = HTML.replace('function render(){', 'function renderBase(){', 1)
HTML = HTML.replace("for(const id of ['batch','search','filter'])", '''
function displayName(name){return name.replace(/-20\\d{6}-\\d{6}(?:-[a-f0-9]+)?$/,'').replaceAll('-',' ').replace(/\\bAV1\\b/g,'AV1')}
function render(){
 renderBase();
 for(const option of $('#batch').options)option.textContent=displayName(option.textContent);
 const batch=batches.find(b=>b.id===$('#batch').value),rows=batch?.episodes||[];
 $('#batch-title').textContent=batch?displayName(batch.name)+' · Episodes':'Episode history';
 const passed=rows.filter(r=>r.verification==='Passed'),sized=passed.filter(r=>Number.isFinite(r.original_bytes)&&Number.isFinite(r.output_bytes));
 const old=sized.reduce((n,r)=>n+r.original_bytes,0),out=sized.reduce((n,r)=>n+r.output_bytes,0);
 const insight=$('#insight');insight.replaceChildren(el('p',old?bytes(old-out)+' saved':'No size evidence yet','insight-total'),el('p',old?'Across '+sized.length+' episodes with recorded sizes':'Results appear after verification completes.','insight-sub'));
 for(const [label,value] of [['Original size',old?bytes(old):'—'],['Encoded size',old?bytes(out):'—'],['Verification',passed.length+' / '+rows.length+' passed'],['Playback approval','Recorded separately from verification']]){const row=el('div',null,'insight-row');row.append(el('span',label),el('span',value));insight.append(row)}
 const notes=['In the selected batch','Automated checks passed','Failed verification or processing','Of verified, measured output'];
 [...$('#summary').children].forEach((card,i)=>card.append(el('small',notes[i],'stat-note')));
 for(const row of $('#episodes').rows){if(row.cells.length!==6)continue;const state=row.cells[1],verification=row.cells[4],review=row.cells[5];const raw=state.textContent;let text=raw,kind='';if(raw.includes('verified')||raw.includes('awaiting playback')){text='Encoded';kind='passed'}else if(raw.includes('fail')){text='Needs attention';kind='failed'}else if(raw==='running'){text='Processing';kind='running'}else if(raw==='pending'){text='Queued'}state.replaceChildren(el('span',text,'state-pill '+kind));const verified=verification.textContent;verification.replaceChildren(el('span',verified==='Passed'?'✓ Passed':verified, 'state-pill '+(verified==='Passed'?'passed':verified==='Failed'?'failed':'')));review.className='review-label';}
 if(!jobs.some(j=>j.state==='running')){const target=$('#active');target.replaceChildren();const block=el('div',null,'live-job');block.append(el('span','✓','idle-icon'),el('strong','All quiet for now'),el('p','No jobs are currently running.'),el('p','Your completed batches and verification results are below.'));target.append(block)}
}
for(const id of ['batch','search','filter'])''',1)

HTML=HTML.replace('Read-only monitor','Playback review monitor').replace('Read-only · Originals protected','Review notes · Media protected')
HTML=HTML.replace("if(!jobs.some(j=>j.state==='running')){", """
 const visible=rows.filter(r=>(r.episode+' '+(r.error||'')).toLowerCase().includes($('#search').value.toLowerCase())&&($('#filter').value==='all'||r.verification===$('#filter').value));
 [...$('#episodes').rows].forEach((tr,i)=>{if(tr.cells.length!==6||!visible[i])return;const r=visible[i],button=el('button','Review','button');button.style.marginTop='8px';button.onclick=()=>reviewEpisode(batch.id,r);tr.cells[5].append(el('br'),button)});
 if(!jobs.some(j=>j.state==='running')){ """,1)
HTML=HTML.replace('async function refresh(){', """
async function reviewEpisode(batch,r){
 const dialog=el('dialog');dialog.style.cssText='border:1px solid #e2e6eb;border-radius:12px;padding:24px;max-width:440px;width:90%';
 dialog.append(el('h2','Playback review · '+r.episode));
 const client=el('select'),status=el('select'),note=el('textarea');
 for(const name of ['Chrome','Sony TV','Plex'])client.append(el('option',name));
 for(const name of ['Not tested','Passed','Failed'])status.append(el('option',name));
 for(const [label,input] of [['Player',client],['Result',status],['Notes',note]]){const wrap=el('label',label);wrap.style.cssText='display:grid;gap:8px;margin:14px 0';input.style.cssText='padding:10px;border:1px solid #d3d9df;border-radius:6px';wrap.append(input);dialog.append(wrap)}note.maxLength=1000;
 const load=()=>{const existing=r.reviews?.[client.value];status.value=existing?.status||'Not tested';note.value=existing?.note||''};client.onchange=load;load();
 const save=el('button','Save review','button primary'),cancel=el('button','Cancel','button'),message=el('p');cancel.style.marginLeft='8px';dialog.append(message,save,cancel);cancel.onclick=()=>{dialog.close();dialog.remove()};dialog.addEventListener('cancel',()=>dialog.remove());
 save.onclick=async()=>{save.disabled=true;try{const response=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({batch,episode:r.review_id,client:client.value,status:status.value,note:note.value})});if(!response.ok)throw Error('Could not save review.');dialog.close();dialog.remove()}catch(e){message.textContent=e.message;save.disabled=false}};
 document.body.append(dialog);dialog.showModal();
}
async function refresh(){""",1)
