"""End-user results: durable archive, stable cards, explicit guarded actions."""
SCRIPT = r'''<script>
let historyLoaded=false,viewState={},batchSignature='',lastControlsUpdate=0,lastCatalogUpdate=0,controlsConnected=false,catalogConnected=false;
function connectionUpdate(kind,ok){if(kind==='controls'){controlsConnected=ok;if(ok)lastControlsUpdate=Date.now()}else{catalogConnected=ok;if(ok)lastCatalogUpdate=Date.now()}
 const last=Math.min(lastControlsUpdate,lastCatalogUpdate),label=last?new Date(last).toLocaleTimeString():'not yet';
 userEl('connection-state').textContent=globalThis.liveUpdatesPaused?'Display paused · jobs continue':(controlsConnected&&catalogConnected?'Connected':'Disconnected · displayed data may be stale')+' · Last full update: '+label;
}
function receiveHistory(body){viewState=body.view||{};connectionUpdate('controls',true);userEl('app-version').textContent=body.app_version||'Unknown (older service)';
 if(!historyLoaded){historyLoaded=true;userEl('result-sort').value=viewState.sort||'newest';userEl('result-filter').value=viewState.filter||'all';userEl('show-archived').checked=!!viewState.show_archived;if(viewState.theme)applyTheme(viewState.theme)}
 userEl('undo-archive').disabled=!(viewState.undo_archive||[]).length;
 const batches=new Map();for(const j of body.jobs||[]){const key=j.batch_id||'folder:'+String(j.source||'').replaceAll('\\','/').split('/').slice(0,-1).join('/');if(!batches.has(key))batches.set(key,{label:j.batch_folder||String(j.source||'').replaceAll('\\','/').split('/').slice(0,-1).join('/'),created:j.created,batch:!!j.batch_id})}
 const sig=JSON.stringify([...batches]);if(sig!==batchSignature){batchSignature=sig;const select=userEl('result-batch'),value=select.value;select.replaceChildren();const all=userNode('option','All folders and batches');all.value='';select.append(all);for(const [key,b] of [...batches].reverse()){const o=userNode('option',b.label+(b.batch?' · '+(b.created?new Date(b.created*1000).toLocaleString():'Date unavailable')+' · '+key.slice(0,6):' · Older work'));o.value=key;select.append(o)}select.value=batches.has(value)?value:(batches.has(viewState.batch)?viewState.batch:'')}
}
function outcomeLabel(job){const raw=String(job.reason||'');if(job.decision_code==='already_efficient_for_settings')return 'Already efficient for tested settings';if(/unsupported|not supported/i.test(raw))return 'Unsupported input';if(job.state==='skipped'&&/quality.*(?:fail|not met|threshold)|quality_pass/i.test(raw))return 'Quality checks not met';if(job.state==='failed')return 'Processing error';return userStatus(job.state)}
function historyKey(j){let s=String(j.source||j.id).replaceAll('\\','/');return /^[A-Za-z]:\//.test(s)?s.toLowerCase():s}
function groupedAttempts(rows){const aliases=new Map();function root(k){while(aliases.has(k)&&aliases.get(k)!==k)k=aliases.get(k);return k}
 for(const j of rows){if(j.published_path){const a=root(historyKey(j)),b=root(historyKey({source:j.published_path}));if(a!==b)aliases.set(b,a)}}
 const groups=new Map();for(const j of rows){const key=root(historyKey(j));if(!groups.has(key))groups.set(key,[]);groups.get(key).push(j)}
 return [...groups].map(([key,attempts])=>{attempts.sort((a,b)=>(b.created||0)-(a.created||0)||outcomeTime(b)-outcomeTime(a)||String(b.id).localeCompare(String(a.id)));return {key,attempts,latest:attempts[0]}})
}
function evidenceText(j){const evidence=j.evidence||{},parts=[];if(Number.isFinite(evidence.estimated_savings_percent))parts.push('Sample estimate: '+evidence.estimated_savings_percent.toFixed(1)+'% smaller (not confirmed full-file savings)');for(const c of evidence.candidates||[]){parts.push(c.id+': '+String(c.assessment||'inconclusive').replaceAll('_',' ')+(Number.isFinite(c.savings_percent)?' · '+c.savings_percent.toFixed(1)+'% sample reduction':'')+(c.quality_evaluated===false?' · quality not evaluated':''))}for(const q of evidence.quality||[])parts.push(q.id+' · measured VMAF samples: '+q.samples.map(s=>'mean '+s.mean.toFixed(2)+', fifth percentile '+s.p5.toFixed(2)+' ('+(s.passed?'passed':'failed')+')').join('; ')+' · metric scores, not percent quality preserved');return parts.join('\n')||'No structured measurement summary in this older record. See the recorded reason and log; missing measurements are not a pass.'}
function savedText(j){if(j.state==='replaced'&&Number.isFinite(j.saved_bytes))return 'Confirmed library reduction: '+(j.saved_bytes/1e9).toFixed(2)+' GB. Retained output copies and snapshots may still use space.';if(Number.isFinite(j.original_bytes)&&Number.isFinite(j.output_bytes)&&j.original_bytes>0)return 'Retained copy: '+sizeSummary(j)+' · no source space reclaimed.';if(Number.isFinite(j.file_savings_percent))return j.file_savings_percent.toFixed(1)+'% file-size change · not confirmed reclaimed space';return ''}
async function historyCall(action,extra={}){const body=await controlCall(action,extra);userEl('history-feedback').textContent=body.message||'Request completed';return body}
function makeResultCard(){const card=userNode('article',null,'result-card'),head=userNode('div',null,'result-header'),name=userNode('h3'),status=userNode('span',null,'badge'),reason=userNode('p',null,'reason'),meta=userNode('p',null,'result-meta'),sizes=userNode('p'),savings=userNode('p',null,'result-meta'),retryNote=userNode('p',null,'attention');head.append(name,status);card.append(head,reason,meta,sizes,savings,retryNote);
 const details=userNode('details'),summary=userNode('summary'),facts=userNode('p',null,'result-meta'),recorded=userNode('p',null,'result-meta'),evidence=userNode('pre'),actions=userNode('div',null,'control-actions'),feedback=userNode('div'),log=userNode('pre');log.hidden=true;log.setAttribute('tabindex','0');evidence.style.whiteSpace='pre-wrap';
 const ref={card,name,status,reason,meta,sizes,savings,retryNote,details,facts,recorded,evidence,job:null,previousNodes:new Map()};
 const logButton=userNode('button','Show diagnostic log');logButton.type='button';logButton.addEventListener('click',async()=>{logButton.disabled=true;try{const j=ref.job;const r=await fetch('/api/request-log?id='+encodeURIComponent(j.requestId||j.id)),b=await r.json();if(ref.job.id!==j.id)return;if(!r.ok)throw Error(b.error||'Log unavailable');log.textContent=b.text;log.hidden=false;log.focus?.()}catch(e){log.textContent=e.message;log.hidden=false}finally{logButton.disabled=false}});
 const inspect=userNode('button','Inspect recovery / cleanup');inspect.type='button';inspect.addEventListener('click',async()=>{inspect.disabled=true;feedback.replaceChildren();try{const j=ref.job,b=await historyCall('inspect-recovery',{job_id:j.id});if(ref.job.id!==j.id)return;feedback.append(userNode('p',b.message));for(const p of b.recovery_files||[])feedback.append(userNode('p','Recovery file: '+p));for(const journal of b.journals||[])feedback.append(userNode('pre',JSON.stringify(journal,null,2)));if(b.cleanup_allowed){const preview=userNode('button','Preview generated-file cleanup');preview.type='button';preview.addEventListener('click',async()=>{preview.disabled=true;try{const d=await historyCall('cleanup-preview',{job_id:j.id});if(ref.job.id!==j.id)return;feedback.append(userNode('p',(d.bytes/1e9).toFixed(2)+' GB generated media · '+d.message));const list=userNode('ul');for(const f of d.files)list.append(userNode('li',f.path));feedback.append(list);if(d.files.length){const confirm=userNode('button','Permanently delete these generated files');confirm.type='button';confirm.addEventListener('click',async()=>{confirm.disabled=true;try{const r=await historyCall('cleanup-confirm',{job_id:j.id,cleanup_id:d.cleanup_id,confirm:true});feedback.append(userNode('p',r.message))}catch(e){feedback.append(userNode('p',e.message))}});feedback.append(confirm)}}catch(e){feedback.append(userNode('p',e.message))}});feedback.append(preview)}}catch(e){feedback.append(userNode('p',e.message))}finally{inspect.disabled=false}});
 const retry=userNode('button','Review retry');retry.type='button';retry.addEventListener('click',async()=>{retry.disabled=true;feedback.replaceChildren();try{const j=ref.job,d=await historyCall('retry-preview',{job_id:j.id});if(ref.job.id!==j.id)return;feedback.append(userNode('p','Retry '+j.source+' · '+d.settings.mode+' · '+d.settings.codec+' · '+d.settings.quality+' · minimum savings '+d.settings.minimum_savings+'%. '+d.original_policy));const blocked=d.files.every(f=>f.history_reason);for(const f of d.files)if(f.history_reason)feedback.append(userNode('p',f.history_reason));if(!blocked){const confirm=userNode('button',d.settings.mode==='replace'?'Approve retry and replace original only after validation':'Confirm retry');confirm.type='button';confirm.addEventListener('click',async()=>{confirm.disabled=true;try{await historyCall('submit',{preview_id:d.preview_id,confirm_replace:d.settings.mode==='replace'});refreshControls()}catch(e){feedback.append(userNode('p',e.message))}});feedback.append(confirm)}}catch(e){feedback.append(userNode('p',e.message))}finally{retry.disabled=false}});
 actions.append(logButton,retry,inspect);details.append(summary,facts,recorded,evidence,actions,feedback,log);card.append(details);const previous=userNode('details'),previousSummary=userNode('summary'),previousBody=userNode('div');previous.append(previousSummary,previousBody);card.append(previous);Object.assign(ref,{summary,retry,inspect,log,feedback,previous,previousSummary,previousBody});return ref;
}
function updateResultCard(ref,group){const j=group.latest;const changed=ref.job&&ref.job.id!==j.id;ref.job=j;if(changed){ref.log.hidden=true;ref.feedback.replaceChildren()}ref.name.textContent=resultName(j);ref.status.textContent=outcomeLabel(j);ref.reason.textContent=userReason(j);ref.meta.textContent=resultMeta(j);ref.sizes.textContent=sizeSummary(j);ref.savings.textContent=savedText(j);ref.retryNote.textContent=['pending','running'].includes(j.state)&&group.attempts.length>1?'Retry '+(j.state==='running'?'running':'queued')+' · previous outcome: '+outcomeLabel(group.attempts[1]):'';
 ref.summary.textContent='Details for '+resultName(j);ref.facts.textContent='Source: '+j.source+'\nRequest: '+(j.requestId||j.id)+'\nApp version: '+(j.app_version||'Unknown (older job)')+'\n'+['created','started','finished'].map((k,i)=>['Queued','Started','Finished'][i]+': '+(Number.isFinite(j[k])?new Date(j[k]*1000).toLocaleString():'Not recorded')).join('\n')+(j.output?'\nOutput: '+j.output:'')+(j.published_path?'\nPublished file: '+j.published_path:'');ref.facts.style.whiteSpace='pre-wrap';ref.recorded.textContent='Recorded reason: '+(j.reason||j.detail||j.error||'Not recorded');ref.evidence.textContent=evidenceText(j);ref.log.setAttribute('aria-label','Diagnostic log for '+resultName(j));ref.retry.hidden=!['failed','interrupted','skipped'].includes(j.state);ref.inspect.hidden=!['failed','interrupted'].includes(j.state);
 const old=group.attempts.slice(1);ref.previous.hidden=!old.length;ref.previousSummary.textContent='Previous attempts ('+old.length+')';const nodes=[];for(const a of old){const key=a.id;let p=ref.previousNodes.get(key);if(!p){p=userNode('p',null,'result-meta');ref.previousNodes.set(key,p)}p.textContent=resultMeta(a)+' · '+outcomeLabel(a)+' · '+userReason(a)+' · Request '+a.id+' · Version '+(a.app_version||'unknown');nodes.push(p)}reconcileNodes(ref.previousBody,nodes);
}
function reconcileNodes(box,nodes){for(const node of [...box.children])if(!nodes.includes(node))node.remove();nodes.forEach((node,i)=>{if(box.children[i]!==node)box.insertBefore(node,box.children[i]||null)})}
function renderHistoryResults(rows,force=false){const query=userEl('result-search').value.toLowerCase(),filter=userEl('result-filter').value||'all',batch=userEl('result-batch').value||'',archived=new Set(viewState.archived_ids||[]),show=userEl('show-archived').checked;
 const visible=rows.filter(j=>(show||['pending','running'].includes(j.state)||!archived.has(j.id))&&(!batch||(j.batch_id||'folder:'+String(j.source||'').replaceAll('\\','/').split('/').slice(0,-1).join('/'))===batch));
 const groups=groupedAttempts(visible).filter(g=>(g.latest.source||'').toLowerCase().includes(query)&&(filter==='history'||(filter==='all'?(resultGroup(g.latest.state)!=='active'||g.attempts.length>1):resultGroup(g.latest.state)===filter)));
 const indexed=new Map(groups.map(g=>[g.latest.id,g]));const sorted=sortedResults(groups.map(g=>g.latest),userEl('result-sort').value||'newest').map(j=>indexed.get(j.id));userEl('result-count').textContent='Showing '+Math.min(resultLimit,sorted.length)+' of '+sorted.length+' matching videos';
 const box=userEl('user-results'),nodes=[];for(const g of sorted.slice(0,resultLimit)){let ref=resultCards.get(g.key);if(!ref){ref=makeResultCard();resultCards.set(g.key,ref)}updateResultCard(ref,g);nodes.push(ref.card)}if(!nodes.length){if(!box.emptyNote)box.emptyNote=userNode('p',null,'control-note');box.emptyNote.textContent=rows.length?'No videos match this filter.':'Your video results will appear here.';nodes.push(box.emptyNote)}
 // Do not move a focused card out from under a keyboard user during polling.
 if(!force&&box.contains?.(document.activeElement)){for(const node of nodes)if(!box.contains(node))box.append(node)}else reconcileNodes(box,nodes);
 userEl('show-results').hidden=sorted.length<=resultLimit;
}
function wireHistory(){async function prefs(values){try{await historyCall('view-preferences',{preferences:values})}catch(e){userEl('history-feedback').textContent=e.message}}
 for(const [id,key,event] of [['result-sort','sort','change'],['result-filter','filter','change'],['theme','theme','change'],['show-archived','show_archived','change']])userEl(id).addEventListener(event,()=>{prefs({[key]:key==='show_archived'?userEl(id).checked:userEl(id).value});renderUserResults(true)});
 userEl('result-batch').addEventListener('change',()=>{resultLimit=20;prefs({batch:userEl('result-batch').value});renderUserResults(true)});
 for(const [id,action] of [['archive-results','archive-results'],['undo-archive','undo-archive']])userEl(id).addEventListener('click',async()=>{userEl(id).disabled=true;try{await historyCall(action);await refreshControls()}catch(e){userEl('history-feedback').textContent=e.message}finally{userEl(id).disabled=id==='undo-archive'&&!(viewState.undo_archive||[]).length}});
}
</script>'''
