"""Compare media semantics, not container-generated identifiers or time bases."""
from fractions import Fraction


def equivalent_stream_language(left, right):
    """Compare ffprobe stream languages; omitted and ISO-639 'und' are unknown.

    FFprobe omits an explicit Matroska 'und' track language, while exposing
    the same value from MP4. Never equate a known language with missing data,
    nor treat empty/invalid strings or 'zxx' (no linguistic content) as 'und'.
    This applies to stream tags, not raw Matroska defaults or chapter tags.
    """
    return left == right or (left in (None, 'und') and right in (None, 'und'))


def canonical_tags(tags, context='metadata'):
    if not isinstance(tags, dict):
        raise ValueError(f'Invalid tags in {context}')
    result = {}
    for name, value in tags.items():
        key = name.casefold()
        if key in result and result[key] != value:
            raise ValueError(f'Conflicting metadata keys in {context}: {key}')
        result[key] = value
    return result


def canonical_chapters(chapters):
    result=[]
    for chapter in chapters:
        timing={}
        for name in ('start','end'):
            try:
                if name in chapter and 'time_base' in chapter:
                    value=Fraction(str(chapter[name]))*Fraction(chapter['time_base'])
                else:
                    value=Fraction(chapter[name+'_time'])
            except (KeyError,ValueError,ZeroDivisionError,TypeError) as exc:
                raise ValueError('Invalid chapter timing: '+name) from exc
            timing[name]=value
        if timing['start']<0 or timing['end']<timing['start']:
            raise ValueError('Invalid chapter interval')
        # Matroska ChapterUID is generated by the muxer. It is not a title,
        # timestamp or ordering property. Keep all other unknown properties.
        extra={k:v for k,v in chapter.items() if k not in
               ('id','time_base','start','end','start_time','end_time','tags')}
        result.append(dict(**timing,tags=canonical_tags(chapter.get('tags',{}),'chapter'),extra=extra))
    return result


def equivalent_ratio(left,right):
    if left==right:return True
    try:
        a=Fraction(str(left).replace(':','/'));b=Fraction(str(right).replace(':','/'))
        return a>0 and b>0 and a==b
    except (ValueError,ZeroDivisionError):
        return False


def compatible_measured_rate(left, right, verified_frame_count):
    """Permit tiny average-rate rounding only after independent frame validation.

    Not used for SAR or declared frame-rate conversion. Bound implied cumulative
    cadence drift by the existing 2ms timeline tolerance over the full evidence.
    Callers must first compare every decoded frame's geometry/count/timestamp.
    """
    if equivalent_ratio(left, right):
        return True
    if type(verified_frame_count) is not int or verified_frame_count < 2:
        return False
    try:
        a, b = Fraction(str(left)), Fraction(str(right))
        return (a > 0 and b > 0 and abs(a-b)/max(a,b) <= Fraction(1, 10**6)
                and abs(1/a-1/b)*verified_frame_count <= Fraction(1,500))
    except (ValueError, ZeroDivisionError, TypeError):
        return False
