"""Compare media semantics, not container-generated identifiers or time bases."""
from fractions import Fraction
import math


def preflight_metadata(data):
    """Validate structural metadata, not arbitrary codec/resolution preferences."""
    streams=data.get('streams',[])
    indices=[s.get('index') for s in streams]
    if not streams or any(type(i) is not int or i<0 for i in indices) or len(set(indices))!=len(indices):
        raise ValueError('Invalid or duplicate source stream identities')
    try:duration=float(data['format']['duration'])
    except (KeyError,ValueError,TypeError) as exc:raise ValueError('Missing or invalid source duration') from exc
    if not math.isfinite(duration) or duration<=0:raise ValueError('Invalid source duration')
    canonical_tags(data.get('format',{}).get('tags',{}),'container')
    for stream in streams:
        canonical_tags(stream.get('tags',{}),'stream '+str(stream['index']))
    chapters=canonical_chapters(data.get('chapters',[]))
    return dict(streams=len(streams),chapters=len(chapters),duration_seconds=duration,
                metadata_structure_checked=True,full_video_decode=False)


def equivalent_stream_language(left, right):
    """Compare ffprobe stream languages; omitted and ISO-639 'und' are unknown.

    FFprobe omits an explicit Matroska 'und' track language, while exposing
    the same value from MP4. Never equate a known language with missing data,
    nor treat empty/invalid strings or 'zxx' (no linguistic content) as 'und'.
    This applies to stream tags, not raw Matroska defaults or chapter tags.
    """
    return left == right or (left in (None, 'und') and right in (None, 'und'))


def canonical_tags(tags, context='metadata'):
    if not isinstance(tags, dict):
        raise ValueError(f'Invalid tags in {context}')
    result = {}
    for name, value in tags.items():
        key = name.casefold()
        if key in result and result[key] != value:
            raise ValueError(f'Conflicting metadata keys in {context}: {key}')
        result[key] = value
    return result


def canonical_chapters(chapters):
    result=[]
    for chapter in chapters:
        timing={}
        for name in ('start','end'):
            try:
                if name in chapter and 'time_base' in chapter:
                    value=Fraction(str(chapter[name]))*Fraction(chapter['time_base'])
                else:
                    value=Fraction(chapter[name+'_time'])
            except (KeyError,ValueError,ZeroDivisionError,TypeError) as exc:
                raise ValueError('Invalid chapter timing: '+name) from exc
            timing[name]=value
        if timing['start']<0 or timing['end']<timing['start']:
            raise ValueError('Invalid chapter interval')
        # Matroska ChapterUID is generated by the muxer. It is not a title,
        # timestamp or ordering property. Keep all other unknown properties.
        extra={k:v for k,v in chapter.items() if k not in
               ('id','time_base','start','end','start_time','end_time','tags')}
        result.append(dict(**timing,tags=canonical_tags(chapter.get('tags',{}),'chapter'),extra=extra))
    return result


def equivalent_ratio(left,right):
    if left==right:return True
    try:
        a=Fraction(str(left).replace(':','/'));b=Fraction(str(right).replace(':','/'))
        return a>0 and b>0 and a==b
    except (ValueError,ZeroDivisionError):
        return False


def compatible_measured_rate(left, right, verified_frame_count):
    """Permit tiny average-rate rounding only after independent frame validation.

    Not used for SAR or declared frame-rate conversion. Bound implied cumulative
    cadence drift by the existing 2ms timeline tolerance over the full evidence.
    Callers must first compare every decoded frame's geometry/count/timestamp.
    """
    if equivalent_ratio(left, right):
        return True
    if type(verified_frame_count) is not int or verified_frame_count < 2:
        return False
    try:
        a, b = Fraction(str(left)), Fraction(str(right))
        return (a > 0 and b > 0 and abs(a-b)/max(a,b) <= Fraction(1, 10**6)
                and abs(1/a-1/b)*verified_frame_count <= Fraction(1,500))
    except (ValueError, ZeroDivisionError, TypeError):
        return False
def display_matrix(stream):
    """Read the complete fixed-point transform, not just a lossy rotation angle."""
    records=[s for s in stream.get('side_data_list',[]) if s.get('side_data_type')=='Display Matrix']
    if not records:return None
    if len(records)!=1:raise ValueError('Ambiguous display matrices')
    rows=str(records[0].get('displaymatrix','')).strip().splitlines()
    if len(rows)!=3:raise ValueError('Incomplete display matrix')
    values=[]
    for row in rows:
        fields=row.split(':',1)
        if len(fields)!=2:raise ValueError('Invalid display matrix row')
        numbers=fields[1].split()
        if len(numbers)!=3:raise ValueError('Invalid display matrix dimensions')
        try:values.extend(int(n) for n in numbers)
        except ValueError:raise ValueError('Invalid display matrix coefficient') from None
    if any(not -(2**31)<=n<2**31 for n in values):raise ValueError('Display matrix coefficient out of range')
    return tuple(values)


def mp4_clock_options(streams):
    """Keep edit-list offsets on an exact common source clock, not 1 ms."""
    clock=1
    for stream in streams:
        if stream.get('time_base'):
            base=Fraction(stream['time_base'])
            if base<=0:raise ValueError('Invalid source track clock')
            clock=math.lcm(clock,base.denominator)
    if clock>2147483647:raise ValueError('Source clocks exceed exact MP4 movie timescale range')
    return ['-movie_timescale',str(clock)]
